config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'

  devise_for :users

  resources :activities
  
  resources :profiles do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_conversation, only: [:index, :create]

  def index
    @conversation_messages = Message.where(conversation_id: @conversation.id)

    @message = Message.new
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.conversation_id = @conversation.id
    profile = Profile.find(@conversation.profile_b_id)

    # sets the user initiating contact as profile_a
    current_user.id == profile.user_id ? @message.from_profile_a = false : @message.from_profile_a = true

    respond_to do |format|
      if @message.save
        format.html { redirect_to conversation_messages_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_with(model: @message, url: { controller: 'messages', action: 'create'}, local: false) do |form| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <p>We've been unable to send your message due to <%= pluralize(@message.errors.count, "error") %></p>

          <ul>
          <% @message.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= form.label :content, 'Message' %>
        </div>
        <div class="col-md-8">
        <%= form.text_area :content, rows: 5, class: "form-control", placeholder: "Enter your message", autofocus: true  %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= form.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Messages</h1>
<% @conversation_messages.each do |message| %>
  <div>
    <% if message.from_profile_a %>
      <% if message.conversation.profile_a.user_id == current_user.id %>
        <div>
          <figure>
            <%= image_tag message.conversation.profile_a.profile_photo_url(:thumb) %>
          </figure>
          <p><%= message.conversation.profile_a.first_name %>(you)</p>
        </div>
      <% else %>
        <p><%= message.conversation.profile_a.first_name %></p>
      <% end %>
    <% else %>
      <% if message.conversation.profile_b.user_id == current_user.id %>
        <div>
          <figure>
            <%= image_tag message.conversation.profile_b.profile_photo_url(:thumb) %>
          </figure>
          <p><%= message.conversation.profile_b.first_name %> (you)</p>
        </div>
      <% else %>
        <p><%= message.conversation.profile_b.first_name %></p>
      <% end %>
    <% end %>
    <p><%= message.content %></p>
  </div>
<% end %>

<%= render 'form' %>

<% if current_user.id == @conversation.profile_b.user_id %>
  <%= link_to 'Back to inbox', profile_conversations_path(@conversation.profile_b) %>
<% else %>
  <%= link_to "Back to #{@conversation.profile_b.first_name}'s profile", profile_path(@conversation.profile_b) %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_with(model: @message, url: { controller: 'messages', action: 'create'}, local:true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <p>We've been unable to send your message due to <%= pluralize(@message.errors.count, "error") %></p>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :content, 'Message' %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>From profile a:</strong>
  <%= @message.from_profile_a %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>