config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'

  devise_for :users

  resources :activities
  
  resources :profiles do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  include ProfileImageUploader[:profile_photo]

  belongs_to :user
  has_many :activities
  has_many :conversations

  accepts_nested_attributes_for :activities

  # validates :first_name, :last_name, :profile_photo, :bio, presence: true
  # validates :postcode, length: { maximum: 4 }, numericality: { only_integer: true, greater_than: 0799, less_than: 7800 }
  # validates :contact_number, length: { maximum: 10 }, numericality: { only_integer: true }

  def self.search(query)
    if query
      where('postcode LIKE ?', "%#{query}%")
    else
      all
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all
    @search_profiles_by_postcode = Profile.search(params[:query])
  end

  def show
    if current_user.present?
      @active_conversation = Conversation.find_by(profile_a_id: current_user.id, profile_b_id: @profile.user_id)
    end

    response = HTTParty.get("http://v0.postcodeapi.com.au/suburbs/#{@profile.postcode}.json")
    @suburbs = []
    response.each { |suburb| @suburbs << suburb['name'] }

  end

  def new
    @profile = Profile.new
    @activity = @profile.activities.build
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :postcode, :profile_photo, :bio, :contact_number, :remove_profile_photo, :query, activities_attributes: [:name, :skill_level])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= render 'shared/errors', obj: @profile %>

<div class = "row">
  <div class = "col-md-12">
    <%= form_with(model: profile, local: true) do |form| %>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= form.label :first_name %>
        </div>
        <div class = "col-md-8">
          <%= form.text_field :first_name, id: :profile_first_name, class: "form-control", placeholder: "Enter your first name", autofocus: true %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= form.label :last_name %>
        </div>
      <div class = "col-md-8">
          <%= form.text_field :last_name, id: :profile_last_name, class: "form-control", placeholder: "Enter your last name" %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= form.label :postcode %>
        </div>
      <div class = "col-md-8">
          <%= form.text_field :postcode, id: :profile_postcode, class: "form-control", placeholder: "eg. 3000" %>
        </div>
      </div>
      <div class = "form-group">
        <div class = "control-label col-md-2">
          <%= form.label :bio %>
        </div>
      <div class = "col-md-8">
          <%= form.text_area :bio, rows: 5, id: :profile_postcode, class: "form-control", placeholder: "Enter some details about yourself!" %>
        </div>
      </div>

    <%= form.fields_for :activities do |activities_form| %>
      <div class="form-group">
        <div class = "col-md-12">
          <%= activities_form.label :activity, "Please select one exercise you'd like a buddy for to begin with. Don't worry, you can add more later!" %>
        </div>
        <div class="dropdown col-md-2">
        <%= activities_form.select :name, options_for_select(["Walking", "Hiking", "Jogging", "Running", "Sprinting", "Long Distance", "Pram"], selected: "Jogging") %>
        </div>
      </div>
      <div class="form-group">
        <div class = "col-md-12">
          <%= activities_form.label :skill_level, 'What is your current skill level?' %>
        </div>
        <div class="dropdown col-md-2">
          <%= activities_form.select :skill_level, options_for_select(["Beginner", "Intermediate", "Advanced", "Expert"], selected: "Beginner") %>
        </div>
        <% end %>
      </div>

    <div class = "form-group">
      <div class = "control-label col-md-2">
        <%= form.label :contact_number %>
      </div>
    <div class = "col-md-8">
        <%= form.text_field :contact_number, id: :profile_contact_number, class: "form-control", placeholder: "e.g 0411 111 111" %>
      </div>
    </div>

    <div class = "form-group">
      <div class = "control-label col-md-2">
        <%= form.label :profile_photo %>
      </div>
      <div class = "col-md-8">
      <%= form.file_field :profile_photo, id: :profile_profile_photo %>
      </div>
    </div>

    <!-- <%# if profile.profile_photo_data? %>
      <div class="field">
        <%#= image_tag profile.profile_photo_url(:thumb) %>
      </div>
      <div class="field">
        Remove attachment: <%= form.check_box :remove_image %>
      </div>
    <%# end %> -->

    <div class = "form-group">
      <div class = "col-md-offset-2 col-md-10">
        <%= form.submit class: "btn btn-primary btn-lg btn-xlarge" %>
      </div>
    </div>
<% end %>

app/views/profiles/_new_conversation.html.erb
<%= form_with(model: @conversation, url: profile_conversations_path(@profile), local: true) do |form| %>
  <div>
    <%= form.button "Contact #{@profile.first_name}", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div>
  <h3><%= profile.first_name %> <%= profile.last_name %></h3>
  <figure>
    <% if profile.profile_photo_data? %>
      <%= link_to image_tag(profile.profile_photo_url(:thumb)), profile %>
    <% end %>
  </figure>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Buddies</h2>

<h3>Find buddies in your area</h3>

<%= form_with url: profiles_path, local: true, method: :get do |f| %>
  <%= f.label :query, 'Search by postcode' %>
  <%= f.text_field :query %>
  <%= f.submit 'Search' %>
<% end %>

<%= render @search_profiles_by_postcode %>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<section>
  <h2><%= @profile.first_name %> <%= @profile.last_name %></h2>
  <br>
  <figure>
    <%= image_tag @profile.profile_photo_url(:original) %>
  </figure>
  <% if current_user.id == @profile.user_id %>
    <small><%= link_to 'Edit this profile page', edit_profile_path(@profile)%></small>  
  <% end %>
</section>
<br>
<hr />
<br>
<section>
  <% if current_user.id == @profile.user_id %>
    <h3>About me</h3>
  <% else %>
    <h3>About <%= @profile.first_name %></h3>
  <% end %>
  <p>
    <%= simple_format(@profile.bio) %>
  </p>
  <p>
    <strong>Location</strong> 
    <ul>
      <li>Postcode: <%= @profile.postcode %></li>
      <li>Surrounding suburbs:
        <%= @suburbs.join(", ") %>
      </li>
    </ul> 
    
  </p>
  <% if current_user.id == @profile.user_id %>
    <p>
      <strong>Contact number</strong> 
      <ul>
        <li><%= @profile.contact_number %> <small><em>only you can see this</em></small></li>
      </ul>
    </p>
  <% end %>
</section>
<br>
<hr />
<br>
<section>
  
  <% if current_user.id == @profile.user_id %>
    <h3>My Activities</h3>
  <% else %>
    <h3>Activities</h3>
  <% end %>
  
  <table class="table">
    <tr>
      <th>Exercise</th>
      <th>Skill Level</th>
      <% if current_user.id == @profile.user_id %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
    
    <% @profile.activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.skill_level %></td>
        <% if current_user.id == @profile.user_id %>
          <td><%= link_to 'Update', edit_activity_path(activity), class: "btn btn-xs btn-warning" %></td>
          <td><%= link_to 'Delete', activity_path(activity), method: :delete, data: { confirm:'Are you sure you want to delete this activity?' }, class: 'btn btn-xs btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <% if current_user.id == @profile.user_id %>
    <%= link_to 'Add Additional Activities', new_activity_path, class: "btn btn-primary btn-lg" %>
  <% end %>
  
</section>
<br>
<hr />
<br>
    <% if current_user.id == @profile.user_id %>
      <h3>My Conversations</h3>
      <br>
      <ul>
        <li><%= link_to 'View Conversations', profile_conversations_path(@profile) %></li>
      </ul>
    <% else %>
      <% if @active_conversation %>
        <!-- If there is an existing conversation, display link to send a message to the host -->
        <li><%= link_to "Contact #{@profile.first_name}", new_conversation_message_path(@active_conversation) %></li> 
      <% else %>
        <!-- Otherwise display button to start a conversation with the host -->
        <%= render partial: 'new_conversation' %>
      <% end %>
    <% end %>
  </ul>
<br>
<hr/>

<%= link_to 'Back', profiles_path %>