config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'

  devise_for :users

  resources :activities
  
  resources :profiles do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :profile_a, class_name: 'Profile'
  belongs_to :profile_b, class_name: 'Profile'
  has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, only: [:show]
  before_action :set_profile, only: [:index, :create]

  def index
    @conversations = Conversation.where(profile_b: @profile.user_id)
  end

  def show
    @messages = Message.where(conversation_id: @conversation)
  end

  def create
    @conversation = Conversation.new
    @conversation.profile_a_id = current_user.id
    @conversation.profile_b_id = @profile.user_id

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to new_conversation_message_path(@conversation), notice: 'Conversation was successfully started.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render profile_path(@profile) }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    def set_profile
      @profile = Profile.find(params[:profile_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:profile_a_id, :profile_b_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_a_id %>
    <%= form.text_field :profile_a_id, id: :conversation_profile_a_id %>
  </div>

  <div class="field">
    <%= form.label :profile_b_id %>
    <%= form.text_field :profile_b_id, id: :conversation_profile_b_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Your Inbox</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Last update</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.profile_a.first_name %> <%= conversation.profile_a.last_name %></td>
        <td><%= format_date(conversation.updated_at) %></td>
        <td><%= link_to 'View Messages', conversation_messages_path(conversation) %></td>
        <td><%= link_to 'Delete', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p>
  <strong>Profile a:</strong>
  <%= @conversation.profile_a %>
</p>

<p>
  <strong>Profile b:</strong>
  <%= @conversation.profile_b %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>