config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'

  devise_for :users

  resources :activities
  
  resources :profiles do
    resources :conversations
  end

  resources :conversations do
    resources :messages
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :profile
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.profile_id = current_user.profile.id

    respond_to do |format|
      if @activity.save
        format.html { redirect_to profile_path(@activity.profile_id), notice: 'Activity was successfully deleted.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to profile_path(@activity.profile_id), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: profile_path }
      else
        format.html { render :edit }
        format.json { render json: profile_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(@activity.profile_id), notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :skill_level)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= render 'shared/errors', obj: @activity %>

<div class = "row">
  <div class = "col-md-12">    
    <%= form_with(model: activity, local: true) do |form| %>
    
      <div class="form-group">
        <div class="control-label col-md-12">
          <%= form.label :name, 'Preferred exercise type' %>
        </div>
        <div class = "col-md-8" %>
          <%= form.select :name, options_for_select(["Walking", "Hiking", "Jogging", "Running", "Sprinting", "Long Distance", "Pram"], selected: @activity.name), id: :activity_name %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-12">
          <%= form.label :skill_level %>
        </div>
        <div class = "col-md-8" %>
          <%= form.select :skill_level, options_for_select(["Beginner", "Intermediate", "Advanced", "Expert"], selected: @activity.skill_level), id: :activity_skill_level %>
        </div>
      </div>
    
      <div class = "form-group">
        <div class = "col-md-offset-2 col-md-10">
          <%= form.submit class: "btn btn-primary btn-md" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/activities/edit.html.erb
<h1>Update Your Preferred Exercise</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', profiles_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profile</th>
      <th>Skill level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.profile %></td>
        <td><%= activity.skill_level %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>Add a New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @activity.profile %>
</p>

<p>
  <strong>Skill level:</strong>
  <%= @activity.skill_level %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>